CREATE TABLE `users` (
  `userId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL DEFAULT '',
  `firstName` VARCHAR(20) NOT NULL DEFAULT '',
  `lastName` VARCHAR(20) NOT NULL DEFAULT '',
  `emailAddress` VARCHAR(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`userId`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;